<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>controlpub</name>
  <version>0.0.1</version>
  <description>Forward Nav2 velocity commands to BYD UART control messages.</description>
  <maintainer email="zpy@example.com">zpy</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>byd_custom_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  <depend>spdlog_wrapper</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
